Features
front-end-by-rimantas/26-grupe-portfolio-docland pull request #22
Opened 2021-04-28 18:19 UTC by MantasUrb

2021-04-28 19:08 UTC, Gytzum requested changes
Ideja ispildyta gerai, bet zinant, kad nesunkiai galima sutrumpinti koda, paliksiu dar ji pataisymui

2021-04-28 19:08 UTC, Gytzum commented on css/components/features.css
> +    background-image: url("/svg/pf1.svg");
manau is features-box(1-4) bei features box(1-4) > i  galetum padaryti 2 aprasymus (Nes pas tave viskas kartojasi, bet tik background-image keiciasi ) taip sutrumpinant koda. taip padaryti gali duodant <i> tagui klase su svg paveiksliuku, o features-box pavadinant visus vienodais klasiu vardais

2021-04-28 19:08 UTC, Gytzum commented on css/components/features.css
> +    position: relative;
Nemanau, kad sitas turi funkcija

2021-04-30 07:58 UTC, Gytzum reviewed
LGTM

2021-04-30 08:00 UTC, bikmanas submitted a review, later dismissed

2021-04-30 08:12 UTC, MantasUrb reviewed
Klaidos perzvelgtos

2021-04-30 08:18 UTC, Gytzum reviewed
LGTM

2021-04-30 11:45 UTC, bikmanas approved these changes

2021-04-30 14:11 UTC, Gytzum approved these changes

2021-04-30 19:29 UTC, merged