About
front-end-by-rimantas/26-grupe-portfolio-docland pull request #29
Opened 2021-04-30 13:33 UTC by bikmanas

NOTE: neatliktos animacijos; Product Ratings dalyje neatliktas Learn More tagas; ir Digital payments nėra check markų (bandau perprasti kaip padaryti. Gal jūs turėsit kokių įžvalgų.) 
Overall, tikiuosi, jog kaip pradinei versijai neblogai.

2021-04-30 19:26 UTC, DeeBee123 requested changes
Šauni užduotis flex'o panaudojimui, o mokėjimas panaudoti flex'ą yra vienas svarbiausių dalykų css!
Stenkis būti atidesnis ir pastabesnis detalėm (font-family, font-size, color, ...), inspect (F12) turi būti tavo geriausias draugas lyginantis su dizainu. Kodo refaktorinimas ateis su laiku, bet būtų gerai jei pradėtum jau dabar.

2021-04-30 19:26 UTC, DeeBee123 commented on css/components/customization.css
> +      max-width: 100%;
kadangi prieš tai suteikėme width šiam elementui, tai turime overridint tą ankstesnį width su nauju. Vietoj max-width: 100% rašyt pvz. width: 90%

2021-04-30 19:26 UTC, DeeBee123 commented on css/components/customization.css
> +      margin: 50px auto 0;
kadangi prieš tai suteikėme width šiam elementui, tai turime overridint tą ankstesnį width su nauju. Vietoj max-width: 80%, rašyti pvz. width:80% ir margin:auto (kad išcentruotų). 

Taip pat nepamiršk, kad vidinius elementus apribojai su max-width tai reiktų čia keisti, kad atitiktų dizainą.

2021-04-30 19:26 UTC, DeeBee123 commented on css/components/customization.css
> +  }
reikalingos media queries mobiliam telefonui ir atkreipk dėmesį, kad dingsta backgroundai. Tam gali tiesiog panaudot display: none arba visibility hidden

2021-04-30 19:26 UTC, DeeBee123 commented on css/components/customization.css
> +
čia naudoji identišką kodą kuris buvo naudojamas  @media (max-width: 991px) . Tai yra nereikalinga, kadangi tu jau anksčiau davei intrukcijas, kad kol ekranas neviršija 991px (nuo 0 iki 991) daryk taip, o dabar tu vėl sakai kol ekranas neviršija 768px daryk taip. 768px įeina į ankstesnę instrukciją.

2021-04-30 22:35 UTC, Gytzum reviewed
vaizdas i ta puse bet content (header, paragraph) turetu but platesnis, ant responsive viskas pasitraukia del margin kuris uzdetas ant 1000 px responsive,  Nemazai padaryta, bet dar idejus truputeli darbo butu gerai :)

2021-05-03 11:54 UTC, bikmanas commented on css/components/customization.css
> +    height: 100%;
Tai taip, jie turi panašų kodą, bet vienas atsiranda iš dešinės pusės, kitas iš kitos. Ir tada pasidaro problema.

2021-05-05 13:38 UTC, closed without merging

2021-05-05 13:38 UTC, bikmanas commented
Old version