fixed-icon issue #40
front-end-by-rimantas/26-grupe-portfolio-docland pull request #41
Opened 2021-05-04 19:48 UTC by DeeBee123

full fixed icon style and functionality

2021-05-06 06:31 UTC, MantasUrb submitted a review, later dismissed
Branch darbo metu nebuvo atnaujintas pagal develop, bet overall atrodo gerai :)

2021-05-06 07:00 UTC, Gytzum reviewed
Yra bugas atsirandant mygtukui, atsirandineja vienoje vietoje ir poto persoka i apacia

2021-05-07 06:28 UTC, minvaitekunas approved these changes, later dismissed
Looks allright

2021-05-07 06:50 UTC, Gytzum submitted a review, later dismissed

2021-05-07 09:01 UTC, MantasUrb approved these changes, later dismissed
Man mygtukas suveikia tik spustelėjus jį du kartus (t.y. pirmas paspaudimas arba nesureaguoja arba sureaguoja ir pavažiuoja per 10-20px. į viršų, o tada sustoja). Antrasis paspaudimas gražina į top kaip priklauso.

2021-05-07 13:10 UTC, bikmanas requested changes
Šiaip viskas gerai, tik tiek, kad galima matyti pradinę stadiją mygtuko. 

Gal į .back-to-top, vietoj visibility, naudok display: none; ir tada kai atsiranda, .show naudoti display: flex, vietoj visibility: visible; 

Žinau, kad keistai skamba, tačiau man padarius taip, nesimatė į kur mygtukas grįžo.

2021-05-10 10:28 UTC, MantasUrb approved these changes
Looks good!

2021-05-24 21:27 UTC, merged