About (ne pilna versija)
front-end-by-rimantas/26-grupe-portfolio-docland pull request #44
Opened 2021-05-05 13:39 UTC by bikmanas

2021-05-05 18:17 UTC, DeeBee123 requested changes
Surašiau visus changes, kuriuos turėtum atlikt norint atitikti dizainą. Jei kažkuri vieta neaiški arba manai, kad neteisinga parašyk man, padiskutuosim. :)

2021-05-05 18:17 UTC, DeeBee123 commented on index.html
> +      <h3>Drag & Drop Feature</h3>
Turi būti ``` <h3>Cash Payment</h3>```

2021-05-05 18:17 UTC, DeeBee123 commented on index.html
> +      <h3>Live Editing</h3>
```<h3>Online Payment</h3>```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  padding: 40px 0 40px 0;
vietoj ```margin-bottom: 30px;
  padding: 40px 0 40px 0;``` turėtų būti ```padding: 0 0 140px 0;```

2021-05-05 18:17 UTC, DeeBee123 commented on index.html
> +<div class="main-container">
pridėk klasę papildoma, nes su last-child man nepavyko permušt stiliaus. ```<div class="main-container last">```

2021-05-05 18:17 UTC, DeeBee123 commented on index.html
> +  <p class="title-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis risus mi. Ut placerat quam lectus. Curabitur dictum velit non lacus ornare tempor. Nullam quis augue.
vietoj
 ``` <p class="title-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis risus mi. Ut placerat quam lectus. Curabitur dictum velit non lacus ornare tempor. Nullam quis augue. <br>Etiam convallis elementum sapien, a aliquam turpis aliquam vitae. Praesent sollicitudin felis vel mi facilisis posuere. Nulla ultrices facilisis justo, non varius nisl semper vel. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>``` 
reikia dvejų ```<p>``` antro ```<p>``` su last-child nepavyko permušt tai uždėjau papildomą klasę 
```<p class="title-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis risus mi. Ut placerat quam lectus. Curabitur dictum velit non lacus ornare tempor.</p><p class="title-description custom">Etiam convallis elementum sapien, a aliquam turpis aliquam vitae. Praesent sollicitudin felis vel mi facilisis posuere. Nulla ultrices facilisis justo, non varius nisl semper vel. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +
pridėk, kad po paskutinio nebūtų padding, nes kitas komponentas jau turi 
```.main-container.last { padding: 0;}```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  height: calc(100% - 100px);
Nelabai suprantu kam čia calc čia reikalingi. Plius 56 eilutė permuša šitą height. Tai tiesiog ištrink šitą eilutę.

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  height: calc(100% - 180px);
```height: 100%;```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  width: 70%;
```width: 80%;```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  width: 75%;
```width: 80%;```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  font-weight: 500;
```font-family: var(--font-family-secondary);``` ištrinti 
```font-weight: 600;``` turi būti

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  margin-left: 50%;
```margin-left: 20%;```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  color: black;
``` color: black;``` ištrinti

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  font-weight: lighter;
```font-weight: lighter;``` ištrinti

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  max-width: 500px;
pridėk 
``` font-family: var(--font-family-secondary); font-weight: 300;```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +
```
.customize:last-child .title-description.custom {
  margin: 14px 0 30px;
}
```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  color: black;
```color: black;``` ištrinti

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  margin-left: 50%;
```
 margin-left: 20%;
  font-family: var(--font-family-secondary);
```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  margin-left: 50%;
```margin-left: 20%;```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +}
praleidai kablelį
```
.check h3,
.check1 h3,
.check2 h3,
.check3 h3 {
  font-size: 24px;
  font-weight: 500;
}
```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +}
praleidai kablelį
```
.check p,
.check1 p,
.check2 p,
.check3 p {
  font-size: 20px;
  color: #707070;
  font-family: var(--font-family-secondary);
}
```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  font-size: 16px;
``` font-size: 18px;```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +
pridėk į media
```
 .customize .title-description,
  .second .second-description{
    max-width: 90%;
    margin:0;
  }

  .check1, .check3 {
    max-width: 90%;
    margin: 0;
  }
```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +    flex-direction: column;
`flex-direction: column-reverse;`

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  }
```
.customize-img,
  .second-img {
    max-width: 60%;
  }
```
ištrinti

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  }
vietoj 
```
 .customize,
  .second {
    max-width: 60%;
    margin-left: 30%;
  }
```
naudoti 
```
 .customize-img,
  .customize,
  .second-img,
  .second {
    width: 80%;
  }
```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +}
į 991 media dar pridėk 
```
.check,
  .check2 {
    max-width: 80%;
  }

  .customize-img,
  .second-img {
    width: 90%;
    max-width: 100%;
  }
  .customize,
  .second {
    max-width: 80%;
    margin: 50px auto 0;
  }
  .customize .customize-title,
  .second .second-title {
    margin: 0 0 10px -10px;
    max-width: 100%;
  }
```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +}
ištrink
```
@media (max-width: 991px) {
  .main-container {
    flex-direction: column;
    align-items: flex-start;
  }

  .second-container {
    flex-direction: column;
    align-items: flex-start;
  }

  .customize-img,
  .second-img {
    max-width: 60%;
  }
  .customize,
  .second {
    max-width: 60%;
    margin-left: 30%;
  }
  .second-container > .second h2 {
    margin-left: 0;
  }
}
```

2021-05-05 18:17 UTC, DeeBee123 commented on css/components/customization.css
> +  }
ištrinti 
```
   flex-direction: column;
    align-items: flex-start;
  }

  .second-container {
    flex-direction: column;
    align-items: flex-end;
  }

  .customize-img,
  .second-img {
    max-width: 60%;
  }
  .customize,
  .second {
    max-width: 60%;
    margin-left: 30%;
  }
```

2021-05-06 06:08 UTC, bikmanas commented
Ačiū Deimante už komentarus. Tiesiog vau. 
Tik turiu tokį klausimą, kai padarau antram elementui margin 20%, visi tekstai yra toliau nuo centro. Ir kai pilnai ištempiu ekraną, gaunasi labai netolygiai: 

![image](https://user-images.githubusercontent.com/49583788/117249604-88bf8d80-ae4a-11eb-9155-51a8adbd9e80.png)

Tad gal reikėtų padaryti vistiek 50%, bet tada media turėčiau kažkaip sužaisti, kad mažintų tą margin'ą. Ne?

2021-05-06 11:27 UTC, bikmanas reviewed
Atnaujinimai atlikti.

2021-05-06 11:29 UTC, bikmanas reviewed
Atlikti atnaujinimai

2021-05-06 18:30 UTC, DeeBee123 submitted a review, later dismissed
👍

2021-05-06 18:55 UTC, MantasUrb approved these changes

2021-05-06 19:58 UTC, DeeBee123 approved these changes

2021-05-06 19:58 UTC, merged