New header with sidemenu
front-end-by-rimantas/26-grupe-portfolio-docland pull request #46
Opened 2021-05-05 16:52 UTC by MariusBudreika

2021-05-05 19:34 UTC, DeeBee123 requested changes
Trūksta animacijos ir stiliaus su icon'ais ir vidinių menu listų.

2021-05-05 19:34 UTC, DeeBee123 commented on css/components/header.css
> +
taip pat man noris cursorio ant menu icon 
```
header .links i {
  cursor: pointer;
}
```

2021-05-05 19:34 UTC, DeeBee123 commented on css/components/header.css
> +  margin-top: 32px;
```
 margin-right: 20px;
  margin-top: 32px;
```
gali būti užrašomi viena eilute `margin: 32px 20px 0 0; `

2021-05-05 19:34 UTC, DeeBee123 commented on css/components/header.css
> +  line-height: 100px;
line-height rekomenduočiau rašyt vienetais, o ne px, nes jei ateityje bus keičiamas font-size proporciškai pasikeistų ir line-height.

2021-05-06 08:34 UTC, MantasUrb approved these changes
Seems good :)

2021-05-06 08:47 UTC, Gytzum approved these changes
LGTM

2021-05-06 08:52 UTC, merged