Footer
front-end-by-rimantas/26-grupe-portfolio-docland pull request #47
Opened 2021-05-05 17:32 UTC by MantasUrb

2021-05-05 19:56 UTC, DeeBee123 requested changes
Labai tvarkingas kodas. Komponentas praktiškai tobulai atitinka dizainą. 💯

2021-05-05 19:56 UTC, DeeBee123 commented on css/components/footer.css
> +}
ant hover dar pačio icon spalva turėtų pasikeist
```
.socials a:hover i {
 color: #593AB1;
}
```

2021-05-05 19:56 UTC, DeeBee123 commented on css/components/footer.css
> +    font-weight: 300;
ubuntu font-family naudojamas visame footer-email tai čia pridėčiau ```font-family: var(--font-family-secondary);```

2021-05-05 19:56 UTC, DeeBee123 commented on css/components/footer.css
> +}
labai minimaliai mato bet ant šito button hover užsideda dar opacity. ```#footer-email-btn:hover {opacity: 0.9}```

2021-05-06 06:55 UTC, MantasUrb commented on css/components/footer.css
> +    font-weight: 300;
Ne visai taip - headeris h3 ir mygtukas 'signup' naudoja primary (Hindi), o paragrafas (secondary).

2021-05-06 06:55 UTC, MantasUrb commented on css/components/footer.css
> +}
liuks, pataisiau :)

2021-05-06 07:10 UTC, MariusBudreika approved these changes

2021-05-06 07:10 UTC, Gytzum approved these changes
LGTM

2021-05-06 07:13 UTC, DeeBee123 requested changes

2021-05-06 07:13 UTC, DeeBee123 commented on css/components/footer.css
> +    color: #707070;
placeholder fontas Arial, o turi būti Ubuntu. Ir kai type'ini juodas fontas

2021-05-06 08:06 UTC, bikmanas submitted a review, later dismissed

2021-05-06 08:06 UTC, Gytzum approved these changes
LGTM

2021-05-06 08:25 UTC, MantasUrb commented on css/components/footer.css
> +    color: #707070;
sutvarkiau :)

2021-05-06 08:28 UTC, MantasUrb commented on css/components/footer.css
> +    color: #707070;
sutvarkiau

2021-05-06 08:41 UTC, Gytzum approved these changes
LGTM

2021-05-06 08:43 UTC, MariusBudreika approved these changes

2021-05-06 08:43 UTC, merged