Customer reviews
front-end-by-rimantas/26-grupe-portfolio-docland pull request #53
Opened 2021-05-06 10:31 UTC by minvaitekunas

Innactive buttons, "drag" function . 
wrong img link.

2021-05-07 07:26 UTC, bikmanas commented
![image](https://user-images.githubusercontent.com/49583788/117413354-8c244900-af1e-11eb-9ccd-1c0daeffc23d.png)
pas mane tik tiek terodo. Naujai pasifetchinau, tačiau niekas nepasikeitė. Čia jaučiu kertasi su kažkieno css.

2021-05-07 09:04 UTC, MantasUrb commented on css/main/layout.css
> +    display: grid;
Atsiradęs horizontalus scrollas, užkomentavus 18 eilutę, scrollas dingsta.

2021-05-07 09:08 UTC, MantasUrb requested changes
Nematau visiškai jokio turinio tavo dalyje. Jeigu norėtum/planuoji sujungti savo dalį į develop/master privalai atlikti šiuos veiksmus:
1. Išspręsti konfliktus, kurie kyla "css/home.css" ir "css/main/layout.css";
2. Padaryti, kad tavo turinys matytųsi;
3. Tavo turinys neišdarkyti kitų jau atliktų darbų visame responsive scale;

Šiaip jeigu visgi norėtum užsibaigti savo dalį bent dalinai, dėl stiliau, lygiavimo ir t.t. gali kreiptis, pagelbėsiu kiek suprasiu. Dėl funkcionalumo nesigilinsiu, pats noob'as esu :D

2021-05-07 12:00 UTC, bikmanas requested changes
Aš sakyčiau, kad gerai turi pasigilinti su layout.css dalimi. Nes kaip ir atvaizduoja, tačiau numuša kitų žmonių css, pvz Mariaus kvadratai visi į šoną nuėję. 
Kaip Marius minėjo, nuėmus 18 eilutę, scrollas dingsta, tačiau abu elementai (customer review) patampa per visą ekraną. 

Manau overall, gal išeitų pabandyti tiesiog savo stiliumi sužaisti ir padaryti ką nors, nes naudojant Rimanto styles, išdarko likusias puslapio dalis.

2021-05-10 10:25 UTC, MantasUrb commented
Konfliktai "css/home.css" ir "css/main/layout.css" neišspręsti, antroji Mariaus "Squares" skiltis nesiligiuoja.

2021-05-24 21:32 UTC, merged